version: "3.9"

services:
  mongo:
    ports:
      - "27017:27017"
    image: mongo:4.0
    environment:
      #      MONGO_INITDB_ROOT_USERNAME: user
      #      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: customers
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 30s
